### PR TITLE
Patch libs that attempt to load with stack execution enabled on linux.

### LINKED ISSUE #4: FMOD Native Binaries Fail to Load on Hardened Linux Systems
### Description:

**Note:** This report contains information originally reported on the Wildermyth discord. More info can be found here: https://discord.com/channels/505370324750172170/550346040960614402/1376308831168237569

On modern Linux distributions with memory protection or hardened kernels (ex: Bazzite), the FMOD native libraries fail to load due to being marked as requiring an executable stack when they were compiled. This results in an UnsatisfiedLinkError, and audio fails to initialize.

I've done some testing, and FMOD appears to function correctly without an executable stack, indicating that this permission is not actually required and may be an artifact of how the native libraries were compiled.

## Steps to reproduce:
1. Launch a game or application that uses fmod-jni on a Linux system with executable stack protections. (Ex: Wildermyth on Bazzite)
2. Observe FMOD failing to load at runtime.

## Observed Behavior:
Audio fails to initialize and no sound is played with the following stacktrace: (from Wildermyth)

```
0:08:214 5 AudioManager failed to load /fmod_runtimes/libfmod.so with java.lang.UnsatisfiedLinkError: /var/home/bazzite/.local/share/Steam/steamapps/common/Wildermyth/.temp/2915597719/fmod_runtimes/libfmod.so: /var/home/bazzite/.local/share/Steam/steamapps/common/Wildermyth/.temp/2915597719/fmod_runtimes/libfmod.so: cannot enable executable stack as shared object requires: Invalid argument: java.lang.UnsatisfiedLinkError: /var/home/bazzite/.local/share/Steam/steamapps/common/Wildermyth/.temp/2915597719/fmod_runtimes/libfmod.so: /var/home/bazzite/.local/share/Steam/steamapps/common/Wildermyth/.temp/2915597719/fmod_runtimes/libfmod.so: cannot enable executable stack as shared object requires: Invalid argument
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at org.fmod.FMODLoader.tryLoad(FMODLoader.java:164)
    at org.fmod.FMODLoader.loadLibrary(FMODLoader.java:137)
    at org.fmod.FMODLoader.loadNativeLibraryFromJar(FMODLoader.java:79)
    at org.fmod.FMODLoader.loadNatives(FMODLoader.java:62)
    at com.worldwalkergames.legacy.context.AudioManager.loadNatives(AudioManager.java:192)
    at com.worldwalkergames.legacy.context.AudioManager.initializeFmodStep1(AudioManager.java:148)
    at java.lang.Thread.run(Thread.java:748)
```

## Environment:

Image

## Potential Fixes:
* You could make this a WONTFIX, and require downstream components to ensure they have a version of fmod that is compiled without stack execution. However some old versions of FMOD may or may not be compiled correctly.

* Offending libraries could be modified before they are passed to System.loadLibrary(). This has advantage of preserving compatibility with versions of FMOD that were compiled with stack execution enabled.

### PR DESCRIPTION
**Pull request by Gamebuster19901**
On some Linux systems, libfmod.so fails to load with the following error:

```
cannot enable executable stack as shared object requires: Invalid argument
```

This is due to the `.so` binary being marked as requiring an executable stack, which is blocked by hardened systems.

The executable stack requirement does not appear to be needed, so this PR ensures that any binaries loaded are stripped of that flag as the binaries are extracted/stored. This should resolve the FMOD loading error without affecting functionality. I've done some light testing on Ubuntu, and the modified binaries seem to work fine.

There are also probably some minor performance gains, as these changes incidentally avoid duplicate `getResourceAsStream` calls due to the nature of the fix.

**__While I've done some tests with Wildermyth on my system, I recommend additional testing before this is used in production.__**

Fixes https://github.com/NateAustin/fmod-jni/issues/4

### CODE REVIEW

**Review by NateAustin — APPROVED** [review]

File: fmod-jni-jar/java_api_src/org/fmod/FMODLoader.java [hunk 1]
```diff
@@ -179,56 +181,71 @@ private static void failWithError(String sharedLibName, Throwable t) {
...
-			
-			InputStream input = null;
+
 			FileOutputStream output = null;
 			try {
-				// Extract native from classpath to temp dir.
-				input = FMODLoader.class.getResourceAsStream(sharedLibName);
-				if (input == null) return null;
+				// Extract native from buffer to temp dir
+				if (libBytes == null) return null;
```
Comment (NateAustin) [inline fmod-jni-jar/java_api_src/org/fmod/FMODLoader.java:242]: This is failing - if the native lib hasn't been extracted, libBytes will be null - we need to extract it here, not return null. Audio is broken (on windows?) (for machines that are playing for the first time?)

**Comment by NateAustin** [comment]
I had to revert this, failing to extract the library if it hasn't already been extracted.
